language: java

before_install: wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
install: mvn dependency:resolve dependency:resolve-plugins
before_script: java -version
script: mvn clean verify

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk9
      after_success: mvn jacoco:report
    - jdk: openjdk9
    - jdk: oraclejdk10
    - jdk: openjdk10
    - jdk: oraclejdk11
      script: mvn clean verify -Dspotbugs.skip=true
    - jdk: openjdk11
      script: mvn clean verify -Dspotbugs.skip=true
    - jdk: oraclejdk-ea
      script: mvn clean verify -Dspotbugs.skip=true
    - jdk: openjdk-ea
      script: mvn clean verify -Dspotbugs.skip=true

  allow_failures:
    - jdk: oraclejdk11
    - jdk: openjdk11
    - jdk: oraclejdk-ea
    - jdk: openjdk-ea

